/** Core searchable entities are normalized in migrations; JSONB is limited to bounded artifacts/configuration. */
export const requiredTables = [
  "accounts",
  "contacts",
  "prospects",
  "source_records",
  "import_runs",
  "source_documents",
  "evidence_claims",
  "evidence_relations",
  "research_runs",
  "research_tasks",
  "reasoning_steps",
  "scoring_policies",
  "scorecards",
  "prospect_decisions",
  "customer_stories",
  "sequences",
  "outreach_drafts",
  "review_events",
  "action_events",
  "calibration_rules",
  "workflow_preferences",
  "saved_views",
  "background_jobs",
  "audit_events",
  "dashboard_exports",
] as const;
export type RequiredTable = (typeof requiredTables)[number];
